/**
 * License key tooling for Readable Capture PDF.
 *
 * Keys are ECDSA P-256 signatures over a small JSON payload. The extension
 * bundles ONLY the public key and verifies keys offline; keys can only be
 * minted by whoever holds the private key (you, and your Stripe fulfillment
 * worker). Nothing secret ever ships inside the extension.
 *
 * Usage:
 *   node scripts/license-tools.mjs keygen
 *     Generates secrets/license-signing-key.json (PRIVATE — never commit,
 *     never ship) and writes the public key into
 *     src/shared/licensePublicKey.ts (safe to commit).
 *
 *   node scripts/license-tools.mjs issue [--master] [--note "text"]
 *     Mints a license key string.
 *
 *   node scripts/license-tools.mjs verify <key>
 *     Verifies a key against the public key and prints its payload.
 */
import { generateKeyPairSync, createPrivateKey, createPublicKey, createSign, createVerify, randomBytes } from 'node:crypto';
import { mkdirSync, writeFileSync, readFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const SECRETS_DIR = join(root, 'secrets');
const PRIVATE_KEY_PATH = join(SECRETS_DIR, 'license-signing-key.json');
const PUBLIC_KEY_TS_PATH = join(root, 'src', 'shared', 'licensePublicKey.ts');
const KEY_PREFIX = 'RCPDF';

const b64url = (buf) => Buffer.from(buf).toString('base64url');

function keygen() {
  if (existsSync(PRIVATE_KEY_PATH)) {
    console.error(
      `Refusing to overwrite ${PRIVATE_KEY_PATH}.\n` +
        'Existing customer keys would stop validating. Delete it manually if you really mean to rotate.',
    );
    process.exit(1);
  }
  // A fresh clone has the (committed) public key but not the private one.
  // Regenerating here would ship a new public key that no sold license
  // verifies against — every customer would drop to the free tier.
  if (existsSync(PUBLIC_KEY_TS_PATH) && readFileSync(PUBLIC_KEY_TS_PATH, 'utf8').includes('"kty"')) {
    console.error(
      `Refusing to overwrite ${PUBLIC_KEY_TS_PATH} — it already holds a live public key\n` +
        'but the matching private key is missing here. Restore secrets/license-signing-key.json\n' +
        'from your backup instead. (Delete the public key file manually only to rotate EVERYTHING.)',
    );
    process.exit(1);
  }
  const { privateKey, publicKey } = generateKeyPairSync('ec', { namedCurve: 'P-256' });
  const privateJwk = privateKey.export({ format: 'jwk' });
  const publicJwk = publicKey.export({ format: 'jwk' });
  mkdirSync(SECRETS_DIR, { recursive: true });
  writeFileSync(PRIVATE_KEY_PATH, JSON.stringify(privateJwk, null, 2), { mode: 0o600 });
  writeFileSync(
    PUBLIC_KEY_TS_PATH,
    `// AUTO-GENERATED by scripts/license-tools.mjs keygen — safe to commit.\n` +
      `// The matching PRIVATE key lives in secrets/license-signing-key.json and\n` +
      `// in the fulfillment worker's env. It must never ship in the extension.\n` +
      `export const LICENSE_PUBLIC_KEY_JWK = ${JSON.stringify(publicJwk)} as const;\n`,
  );
  console.log(`Private key:  ${PRIVATE_KEY_PATH}  (gitignored — keep safe, used by the worker too)`);
  console.log(`Public key:   ${PUBLIC_KEY_TS_PATH}  (embedded in the extension)`);
}

function loadPrivateKey() {
  if (!existsSync(PRIVATE_KEY_PATH)) {
    console.error('No signing key found. Run: node scripts/license-tools.mjs keygen');
    process.exit(1);
  }
  const jwk = JSON.parse(readFileSync(PRIVATE_KEY_PATH, 'utf8'));
  return createPrivateKey({ key: jwk, format: 'jwk' });
}

function issue(args) {
  const master = args.includes('--master');
  const noteIdx = args.indexOf('--note');
  const note = noteIdx !== -1 ? args[noteIdx + 1] : undefined;
  const payload = {
    v: 1,
    k: master ? 'mst' : 'std',
    id: b64url(randomBytes(9)),
    ts: Date.now(),
    ...(note ? { n: String(note).slice(0, 60) } : {}),
  };
  const payloadB64 = b64url(JSON.stringify(payload));
  const signer = createSign('SHA256');
  signer.update(payloadB64);
  // ieee-p1363 matches WebCrypto's ECDSA signature format in the extension.
  const sig = signer.sign({ key: loadPrivateKey(), dsaEncoding: 'ieee-p1363' });
  const key = `${KEY_PREFIX}-${payloadB64}.${b64url(sig)}`;
  console.log(key);
}

function verify(args) {
  const key = args[0];
  if (!key) {
    console.error('Usage: node scripts/license-tools.mjs verify <key>');
    process.exit(1);
  }
  const match = key.trim().match(new RegExp(`^${KEY_PREFIX}-([A-Za-z0-9_-]+)\\.([A-Za-z0-9_-]+)$`));
  if (!match) {
    console.error('Malformed key.');
    process.exit(1);
  }
  const [, payloadB64, sigB64] = match;
  const publicTs = readFileSync(PUBLIC_KEY_TS_PATH, 'utf8');
  const jwk = JSON.parse(publicTs.slice(publicTs.indexOf('= {') + 2, publicTs.indexOf('} as const') + 1));
  const verifier = createVerify('SHA256');
  verifier.update(payloadB64);
  const ok = verifier.verify(
    { key: createPublicKey({ key: jwk, format: 'jwk' }), dsaEncoding: 'ieee-p1363' },
    Buffer.from(sigB64, 'base64url'),
  );
  if (!ok) {
    console.error('INVALID signature.');
    process.exit(1);
  }
  console.log('VALID', JSON.parse(Buffer.from(payloadB64, 'base64url').toString('utf8')));
}

const [, , command, ...rest] = process.argv;
if (command === 'keygen') keygen();
else if (command === 'issue') issue(rest);
else if (command === 'verify') verify(rest);
else {
  console.error('Usage: node scripts/license-tools.mjs <keygen|issue|verify> [...]');
  process.exit(1);
}
